version: '3.7'

services:
  metrics-processor:
    build: ./apps/processor/
    container_name: processor
    restart: always
    environment:
      - POSTGRES_HOST=metrics
      - POSTGRES_PORT=5432
      - POSTGRES_DB=metrics
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=no_password
    depends_on:
      - metrics-db

  metics-db:
    image: postgres:14-alpine
    container_name: metrics
    restart: always
    environment:
      - POSTGRES_DB=metrics
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=no_password
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata-14-metrics:/var/lib/postgresql/data

volumes:
  pgdata-14-metrics:
    driver: local
