version: '3.7'

services:
  processor:
    build: ./microservices/processor/
    container_name: processor
    restart: always
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
      - MQTT_TOPIC=payloads
      - DB_HOST=metrics
      - DB_PORT=5432
      - DB_DB=metrics
      - DB_USER=postgres
      - DB_PASSWORD=no_password
      - ENV=DEV
    depends_on:
      - metrics-db
      - mosquitto

  metrics-db:
    image: postgres:14-alpine
    container_name: metrics
    restart: always
    environment:
      - POSTGRES_DB=metrics
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=no_password
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata-14-metrics:/var/lib/postgresql/data

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: always
    ports:
      - "127.0.0.1:1883:1883"
      - "127.0.0.1:9001:9001"
    volumes:
     - mosquitto.conf:/mosquitto/config/mosquitto.conf

  notifier:
    build: ./microservices/notifications/
    container_name: notifications
    restart: always
    environment:
      - SENDGRID_API_KEY=example
      - SENGRID_FROM_EMAIL=example@example.com
      - SENDGRID_TO_EMAIL=example@example.com
      - PORT=5000
      - ENV=DEV
    depends_on:
      - processor

volumes:
  pgdata-14-metrics:
    driver: local
  mosquitto.conf:
    driver: local
