version: '3.7'

services:
  notifier:
    build: ./microservices/notifications/
    container_name: notifications
    restart: always
    env_file: .env
    depends_on:
      - cache

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
