version: '3.7'

services:
  processor:
    build: .
    container_name: processor
    restart: always
    env_file: ./.env
    depends_on:
      - metrics-db
      - mosquitto

  metrics-db:
    image: postgres:14-alpine
    container_name: metrics
    restart: always
    environment:
      - POSTGRES_DB=metrics
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=no_password
    ports:
      - 5432:5432
    volumes:
      - pgdata-14-metrics:/var/lib/postgresql/data

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
     - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

volumes:
  pgdata-14-metrics:
    driver: local
  mosquitto.conf:
    driver: local
